package game.gui.wizard;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import engine.io.FileManager;
import game.core.InfinityGame;
import game.setup.GameWizard;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class DeleteGameUI {
    public JPanel mainPanel;
    private JLabel deleteGameLabel;
    private JTextField deleteGameField;
    private JLabel gameFoundLabel;
    private JButton deleteGameButton;
    private JButton backButton;
    private JList gameList;

    private boolean fileFound = false;

    public DeleteGameUI(DeleteGameWindow currentWindow) {
        InfinityGame.gameWizard.refreshGameList();

        $$$setupUI$$$();
        deleteGameButton.setEnabled(false);
        gameFoundLabel.setForeground(Color.RED);
        gameFoundLabel.setText("Game Not Found.");

        deleteGameField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void removeUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void insertUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void labelChanged() {
                String saveName = deleteGameField.getText();
                gameList.clearSelection();

                fileFound = FileManager.doesFileExist(saveName + GameWizard.MAIN_SAVE_EXT);

                if (fileFound) {
                    deleteGameButton.setEnabled(true);
                    gameFoundLabel.setForeground(Color.GREEN);
                    gameFoundLabel.setText("Game Found!");
                } else {
                    deleteGameButton.setEnabled(false);
                    gameFoundLabel.setForeground(Color.RED);
                    gameFoundLabel.setText("Game Not Found.");
                }
            }
        });
        deleteGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (fileFound) {
                    currentWindow.dispose();
                    String gamename = deleteGameField.getText();
                    InfinityGame.gameWizard.deleteGame(gamename);
                    new DeleteConfirmationWindow(deleteGameField.getText());
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new GameWizardWindow();
            }
        });
        gameList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (gameList.getSelectedIndex() != -1) {
                    fileFound = true;
                    deleteGameButton.setEnabled(true);
                    gameFoundLabel.setForeground(Color.GREEN);
                    gameFoundLabel.setText("Game Found!");

                    deleteGameField.setText((String) gameList.getSelectedValue());
                }
            }
        });
    }

    private DefaultListModel initializeList() {
        List<String> games = InfinityGame.gameWizard.getGameList();
        DefaultListModel model = new DefaultListModel();

        for (String game : games) {
            model.addElement(game);
        }

        return model;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        gameList = new JList(initializeList());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        deleteGameLabel = new JLabel();
        deleteGameLabel.setText("Game Name:");
        mainPanel.add(deleteGameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteGameField = new JTextField();
        mainPanel.add(deleteGameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        gameFoundLabel = new JLabel();
        gameFoundLabel.setText("Game not found.");
        mainPanel.add(gameFoundLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteGameButton = new JButton();
        deleteGameButton.setText("Delete Game");
        mainPanel.add(deleteGameButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        mainPanel.add(backButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gameList.setEnabled(true);
        gameList.setOpaque(false);
        gameList.setSelectionBackground(new Color(-11626800));
        gameList.setSelectionMode(0);
        mainPanel.add(gameList, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
