package game.gui.wizard;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import engine.io.FileManager;
import game.core.InfinityGame;
import game.setup.GameWizard;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoadGameUI {
    public JPanel mainPanel;
    private JLabel loadGameLabel;
    private JTextField loadGameField;
    private JLabel gameFoundLabel;
    private JButton loadGameButton;
    private JButton backButton;

    private boolean fileFound = false;

    public LoadGameUI(LoadGameWindow currentWindow) {

        loadGameButton.setEnabled(false);
        gameFoundLabel.setForeground(Color.RED);
        gameFoundLabel.setText("Game Not Found.");

        loadGameField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void removeUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void insertUpdate(DocumentEvent e) {
                labelChanged();
            }

            public void labelChanged() {
                String saveName = loadGameField.getText();

                fileFound = FileManager.doesFileExist(saveName + GameWizard.MAIN_SAVE_EXT);

                if (fileFound) {
                    loadGameButton.setEnabled(true);
                    gameFoundLabel.setForeground(Color.GREEN);
                    gameFoundLabel.setText("Game Found!");
                } else {
                    loadGameButton.setEnabled(false);
                    gameFoundLabel.setForeground(Color.RED);
                    gameFoundLabel.setText("Game Not Found.");
                }
            }
        });
        loadGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (fileFound) {
                    currentWindow.dispose();
                    InfinityGame.gameWizard.startGame(InfinityGame.gameWizard.loadGame(loadGameField.getText()));
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new GameWizardWindow();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        loadGameLabel = new JLabel();
        loadGameLabel.setText("Game Name:");
        mainPanel.add(loadGameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loadGameField = new JTextField();
        mainPanel.add(loadGameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        gameFoundLabel = new JLabel();
        gameFoundLabel.setText("Game not found.");
        mainPanel.add(gameFoundLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loadGameButton = new JButton();
        loadGameButton.setText("Load Game");
        mainPanel.add(loadGameButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        mainPanel.add(backButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
