package game.gui.game;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;

import game.core.*;

public class CompanyUI {
    public JPanel mainPanel;
    private JButton backButton;
    private JButton upgradeOfficeButton;
    private JLabel companyLabel;
    private JLabel CEOLabel;
    private JLabel currentFundsLabel;
    private JLabel gamesReleasedLabel;

    public CompanyUI(CompanyWindow currentWindow) {
        initializeLabels();

        upgradeOfficeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new UpgradeOfficeWindow();
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new MainGameWindow();
            }
        });
    }

    public void initializeLabels() {
        companyLabel.setText("[" + GameLoop.gameSave.getProperty("company_name") + "] - " + Reference.getOffice(Integer.parseInt(GameLoop.gameSave.getProperty("company_office"))));
        CEOLabel.setText("CEO: " + GameLoop.gameSave.getProperty("player_name"));
        currentFundsLabel.setText("Current Funds: £" + GameLoop.gameSave.getProperty("company_money"));
        gamesReleasedLabel.setText("Games Released: " + String.valueOf(GameLoop.gameSave.getGames().size()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        upgradeOfficeButton = new JButton();
        upgradeOfficeButton.setText("Upgrade Office");
        mainPanel.add(upgradeOfficeButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        companyLabel = new JLabel();
        companyLabel.setText("[COMPANY]");
        mainPanel.add(companyLabel, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CEOLabel = new JLabel();
        CEOLabel.setText("CEO: [PLAYER]");
        mainPanel.add(CEOLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        currentFundsLabel = new JLabel();
        currentFundsLabel.setText("Current Funds:");
        mainPanel.add(currentFundsLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gamesReleasedLabel = new JLabel();
        gamesReleasedLabel.setText("Games Released:");
        mainPanel.add(gamesReleasedLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Back");
        mainPanel.add(backButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
