package game.gui.game;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import game.core.Game;
import game.core.GameLoop;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;

public class GameUI {

    public JPanel mainPanel;
    private JList gameList;
    private JLabel gameOverviewLabel;
    private JLabel profitLabel;
    private JLabel totalGainLabel;
    private JLabel ratingLabel;
    private JButton backButton;
    private JButton detailsButton;

    private DefaultListModel<String> listModel;

    public GameUI(GameWindow currentWindow) {
        detailsButton.setEnabled(false);

        listModel = new DefaultListModel<>();
        $$$setupUI$$$();
        initializeLabels();

        gameList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                profitLabel.setForeground(Color.BLACK);
                String gameName = (String) gameList.getSelectedValue();
                Game selectedGame = null;

                Iterator<Game> it = GameLoop.gameSave.getGames().iterator();
                while (it.hasNext()) {
                    Game game = it.next();
                    if (game.getName().equalsIgnoreCase(gameName)) {
                        selectedGame = game;
                    }
                }

                gameOverviewLabel.setText(selectedGame.getName() + " - Overview");

                float profit = selectedGame.getProfit();

                if (profit > -1) {
                    profitLabel.setText("Profit: £" + profit);
                } else {
                    profitLabel.setText("Profit: -£" + -profit);
                    profitLabel.setForeground(Color.RED);
                }
                totalGainLabel.setText("Total Gain: £" + selectedGame.getGain());
                ratingLabel.setText("Rating: " + (selectedGame.getRating() * 10) + " / 10");

                detailsButton.setEnabled(true);
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new MainGameWindow();
            }
        });
        detailsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String gameName = (String) gameList.getSelectedValue();
                Game selectedGame = null;

                Iterator<Game> it = GameLoop.gameSave.getGames().iterator();
                while (it.hasNext()) {
                    Game game = it.next();
                    if (game.getName().equalsIgnoreCase(gameName)) {
                        selectedGame = game;
                    }
                }

                new GameDetailWindow(selectedGame);
            }
        });
    }

    private void initializeLabels() {
        gameList.setModel(listModel);
        for (Game game : GameLoop.gameSave.getGames()) {
            listModel.addElement(game.getName());
        }
    }

    private void createUIComponents() {
        gameList = new JList(listModel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        gameList.setBackground(new Color(-1250068));
        gameList.setOpaque(false);
        mainPanel.add(gameList, new GridConstraints(0, 0, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        gameOverviewLabel = new JLabel();
        gameOverviewLabel.setText("Select a Game:");
        mainPanel.add(gameOverviewLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        profitLabel = new JLabel();
        profitLabel.setText("Profit:");
        mainPanel.add(profitLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalGainLabel = new JLabel();
        totalGainLabel.setText("Total Gain:");
        mainPanel.add(totalGainLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ratingLabel = new JLabel();
        ratingLabel.setText("Rating:");
        mainPanel.add(ratingLabel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("Dashboard");
        mainPanel.add(backButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        detailsButton = new JButton();
        detailsButton.setText("Details");
        mainPanel.add(detailsButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
