package game.gui.game;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import game.core.GameLoop;
import game.gui.wizard.GameWizardWindow;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainGameUI {
    public JPanel mainPanel;
    private JButton playerButton;
    private JButton companyButton;
    private JButton employeesButton;
    private JButton gamesButton;
    private JButton menuButton;
    private JList mainConsole;

    private final boolean[] BUTTON_CONFIG = {
            true, // PLAYER
            true, // COMPANY
            false, // EMPLOYEES
            true, // GAMES
            true // MENU
    };

    //TODO- player done, decide on upgrade system
    //TODO- game creation, game saving, game money
    //TODO- make things functional

    public MainGameUI(MainGameWindow currentWindow) {
        updateChat();
        //max chat length: 25 lines

        playerButton.setEnabled(BUTTON_CONFIG[0]);
        companyButton.setEnabled(BUTTON_CONFIG[1]);
        employeesButton.setEnabled(BUTTON_CONFIG[2]);
        gamesButton.setEnabled(BUTTON_CONFIG[3]);
        menuButton.setEnabled(BUTTON_CONFIG[4]);

        playerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new PlayerWindow();
            }
        });
        companyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e)   {
                currentWindow.dispose();
                new CompanyWindow();
            }
        });
        employeesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GameLoop.addChatMessage("Employees button clicked!");
            }
        });
        gamesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new GameWindow();
            }
        });
        menuButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentWindow.dispose();
                new MenuWindow();
            }
        });
    }

    private void updateChat() {
        mainConsole.setModel(GameLoop.mainConsoleLog);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        playerButton = new JButton();
        playerButton.setText("Player");
        mainPanel.add(playerButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        companyButton = new JButton();
        companyButton.setText("Company");
        mainPanel.add(companyButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        employeesButton = new JButton();
        employeesButton.setText("Employees");
        mainPanel.add(employeesButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gamesButton = new JButton();
        gamesButton.setText("Games");
        mainPanel.add(gamesButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        menuButton = new JButton();
        menuButton.setText("Menu");
        mainPanel.add(menuButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mainConsole = new JList();
        mainConsole.setBackground(new Color(-1250068));
        mainConsole.setEnabled(true);
        mainConsole.setFocusable(false);
        mainConsole.setOpaque(true);
        mainConsole.setSelectionMode(0);
        mainPanel.add(mainConsole, new GridConstraints(0, 0, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
